[build]
  functions = "netlify/functions"

[functions.keepalive]
  schedule = "*/5 * * * *"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
